Table publication {
  id int [pk, increment]
  original_id varchar
  source varchar
  pmid float
  pmcid varchar
  fullTextIdList varchar
  doi varchar
  title varchar
  authorString varchar
  authorList varchar
  authorIdList varchar
  dataLinksTagsList varchar
  journalInfo varchar
  pubYear float
  pageInfo varchar
  abstractText varchar
  affiliation varchar
  publicationStatus varchar
  language varchar
  pubModel varchar
  pubTypeList varchar
  meshHeadingList varchar
  subsetList varchar
  fullTextUrlList varchar
  isOpenAccess varchar
  inEPMC varchar
  inPMC varchar
  hasPDF varchar
  hasBook varchar
  hasSuppl varchar
  citedByCount int
  hasData varchar
  hasReferences varchar
  hasTextMinedTerms varchar
  hasDbCrossReferences varchar
  hasLabsLinks varchar
  license varchar
  hasEvaluations varchar
  authMan varchar
  epmcAuthMan varchar
  nihAuthMan varchar
  hasTMAccessionNumbers varchar
  dateOfCompletion varchar
  dateOfCreation varchar
  firstIndexDate varchar
  fullTextReceivedDate varchar
  dateOfRevision varchar
  electronicPublicationDate varchar
  firstPublicationDate varchar
  chemicalList varchar
  keywordList varchar
  tmAccessionTypeList varchar
  grantsList varchar
  commentCorrectionList varchar
  bookOrReportDetails varchar
  versionList varchar
  versionNumber float
}

Table author {
  id int [pk, increment]
  original_id varchar
  source varchar
  pmid float
  pmcid varchar
  fullTextIdList varchar
  doi varchar
  title varchar
  authorString varchar
  authorList varchar
  authorIdList varchar
  dataLinksTagsList varchar
  journalInfo varchar
  pubYear float
  pageInfo varchar
  abstractText varchar
  affiliation varchar
  publicationStatus varchar
  language varchar
  pubModel varchar
  pubTypeList varchar
  meshHeadingList varchar
  subsetList varchar
  fullTextUrlList varchar
  isOpenAccess varchar
  inEPMC varchar
  inPMC varchar
  hasPDF varchar
  hasBook varchar
  hasSuppl varchar
  citedByCount int
  hasData varchar
  hasReferences varchar
  hasTextMinedTerms varchar
  hasDbCrossReferences varchar
  hasLabsLinks varchar
  license varchar
  hasEvaluations varchar
  authMan varchar
  epmcAuthMan varchar
  nihAuthMan varchar
  hasTMAccessionNumbers varchar
  dateOfCompletion varchar
  dateOfCreation varchar
  firstIndexDate varchar
  fullTextReceivedDate varchar
  dateOfRevision varchar
  electronicPublicationDate varchar
  firstPublicationDate varchar
  chemicalList varchar
  keywordList varchar
  tmAccessionTypeList varchar
  grantsList varchar
  commentCorrectionList varchar
  bookOrReportDetails varchar
  versionList varchar
  versionNumber float
}

Table journal {
  id int [pk, increment]
  original_id varchar
  source varchar
  pmid float
  pmcid varchar
  fullTextIdList varchar
  doi varchar
  title varchar
  authorString varchar
  authorList varchar
  authorIdList varchar
  dataLinksTagsList varchar
  journalInfo varchar
  pubYear float
  pageInfo varchar
  abstractText varchar
  affiliation varchar
  publicationStatus varchar
  language varchar
  pubModel varchar
  pubTypeList varchar
  meshHeadingList varchar
  subsetList varchar
  fullTextUrlList varchar
  isOpenAccess varchar
  inEPMC varchar
  inPMC varchar
  hasPDF varchar
  hasBook varchar
  hasSuppl varchar
  citedByCount int
  hasData varchar
  hasReferences varchar
  hasTextMinedTerms varchar
  hasDbCrossReferences varchar
  hasLabsLinks varchar
  license varchar
  hasEvaluations varchar
  authMan varchar
  epmcAuthMan varchar
  nihAuthMan varchar
  hasTMAccessionNumbers varchar
  dateOfCompletion varchar
  dateOfCreation varchar
  firstIndexDate varchar
  fullTextReceivedDate varchar
  dateOfRevision varchar
  electronicPublicationDate varchar
  firstPublicationDate varchar
  chemicalList varchar
  keywordList varchar
  tmAccessionTypeList varchar
  grantsList varchar
  commentCorrectionList varchar
  bookOrReportDetails varchar
  versionList varchar
  versionNumber float
}

Table affiliation {
  id int [pk, increment]
  original_id varchar
  source varchar
  pmid float
  pmcid varchar
  fullTextIdList varchar
  doi varchar
  title varchar
  authorString varchar
  authorList varchar
  authorIdList varchar
  dataLinksTagsList varchar
  journalInfo varchar
  pubYear float
  pageInfo varchar
  abstractText varchar
  affiliation varchar
  publicationStatus varchar
  language varchar
  pubModel varchar
  pubTypeList varchar
  meshHeadingList varchar
  subsetList varchar
  fullTextUrlList varchar
  isOpenAccess varchar
  inEPMC varchar
  inPMC varchar
  hasPDF varchar
  hasBook varchar
  hasSuppl varchar
  citedByCount int
  hasData varchar
  hasReferences varchar
  hasTextMinedTerms varchar
  hasDbCrossReferences varchar
  hasLabsLinks varchar
  license varchar
  hasEvaluations varchar
  authMan varchar
  epmcAuthMan varchar
  nihAuthMan varchar
  hasTMAccessionNumbers varchar
  dateOfCompletion varchar
  dateOfCreation varchar
  firstIndexDate varchar
  fullTextReceivedDate varchar
  dateOfRevision varchar
  electronicPublicationDate varchar
  firstPublicationDate varchar
  chemicalList varchar
  keywordList varchar
  tmAccessionTypeList varchar
  grantsList varchar
  commentCorrectionList varchar
  bookOrReportDetails varchar
  versionList varchar
  versionNumber float
}

// Example relationships - Replace with actual relationships based on your data
Ref: author.publication_id > publication.id
Ref: publication.journal_id > journal.id
Ref: author.affiliation_id > affiliation.id
